Repository nl-design-system/denhaag, pull requests merged in 2021-06, with the labels that each got.

#172 Implemented design for Divider component.
  src/components/Divider/package.json
  src/components/Divider/src/Divider.stories.tsx
  src/components/Divider/src/divider.module.css
  src/components/Divider/src/index.tsx
  src/styles/Components/src/components.module.css
  src/styles/Components/src/tokens-divider.css
Labels: Should discuss, enhancement

#261 Remove yarn-outdated-formatter dependency
  package.json
  yarn.lock
Labels: dependencies

#270 Update storybook dependencies to fix react docgen error
  package.json
  yarn.lock
Labels: bug
